### ISSUE TITLE
Error when running app.py

### ISSUE THREAD

**Issue by cloudorbush** [mrxmamun/bitmex-api-helper#1]
lib\site-packages\swagger_spec_validator\validator20.py:49: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  warnings.warn(
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    def order():
  "\lib\site-packages\flask\app.py", line 1314, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  "\lib\site-packages\flask\app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  "\site-packages\flask\app.py", line 1274, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  "\lib\site-packages\werkzeug\routing.py", line 641, in __init__
    raise ValueError("urls must start with a leading slash")
ValueError: urls must start with a leading slash

**Comment by akmamun** [comment]
@10000multiplier add slash in every URL, like `@app.route("/data/order")` instead of `@app.route("data/order")` . new updated push also fixed this issue.

**Comment by cloudorbush** [comment]
@mrxmamun thanks. New error:

\lib\site-packages\bravado\http_future.py", line 420, in raise_on_expected
    raise make_http_exception(
bravado.exception.HTTPUnauthorized: 401 Unauthorized: {'error': {'message': 'Invalid API Key.', 'name': 'HTTPError'}}
127.0.0.1 - - [01/Jan/2020 02:43:58] "GET /data/instrument HTTP/1.1" 500 -

**Comment by akmamun** [comment]
@10000multiplier  Register or Login https://testnet.bitmex.com. 
go to https://testnet.bitmex.com/app/apiKeys and click Create API Key.
you will get api key and api secret . and add those in app.py , for more see [Readme](https://github.com/mrxmamun/bitmex-api-helper/blob/master/README.md)

**Comment by cloudorbush** [comment]
I have. That’s the error I get.
